name: flutter_objectbox
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  objectbox: ^4.0.1
  objectbox_flutter_libs: ^4.0.1
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.3
  permission_handler: ^11.0.1
  intl: any
  pdf: ^3.11.0
  printing: ^5.13.1
  cron: ^0.6.1
  ntp: ^2.0.0
  syncfusion_flutter_datagrid: ^26.2.11
  pluto_grid:
     git:
      https://github.com/MuhammedKasujja/pluto_grid.git
  pluto_grid_plus: ^8.4.1
  searchfield: ^1.0.9
  flutter_typeahead: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  flutter_lints: ^3.0.0
  objectbox_generator: ^4.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/

 